name: Docker image

on:
  push:
    branches:
    - master
    paths:
    - 'scripts/Dockerfile'
    - 'scripts/properties.sh'
    - 'scripts/setup-android-sdk.sh'
    - 'scripts/setup-ubuntu.sh'
  schedule:
    - cron:  '0 2 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Patch
      run: ./patch-repo.sh
    - name: Build
      run: |
        cd ./scripts
        docker build --tag vanhoavn/vheditor-package-builder:latest .
    - name: Push to hub.docker.com
      env:
        DOCKER_LOGIN: vanhoavn
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        docker login --username "${DOCKER_LOGIN}" --password "${DOCKER_PASS}"
        docker push vanhoavn/vheditor-package-builder:latest
